# Generated by Django 3.1.5 on 2021-01-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('order_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('topping_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(choices=[('sm', 'small'), ('m', 'medium'), ('lg', 'large')], max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4)),
                ('in_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='pizzastore.order')),
                ('toppings', models.ManyToManyField(blank=True, related_name='pizzas', to='pizzastore.Topping')),
            ],
        ),
    ]
