# Generated by Django 3.1.5 on 2021-02-01 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzastore', '0004_auto_20210128_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzast', to='pizzastore.Topping'),
        ),
    ]
